"""Exporting transforms as files Resolve and Premiere can load."""

from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import escape

import numpy as np

from .match import Transform


def sample_lattice(transform: Transform, size: int = 33) -> np.ndarray:
    """Evaluate a transform over a size**3 RGB cube.

    Returned in .cube ordering: red varies fastest, then green, then blue.
    """
    if size < 2 or size > 128:
        raise ValueError("LUT size must be between 2 and 128 (33 is standard).")

    axis = np.linspace(0.0, 1.0, size)
    # indexing="ij" over (b, g, r) then stacking as RGB gives red-fastest when
    # the result is flattened in C order.
    b, g, r = np.meshgrid(axis, axis, axis, indexing="ij")
    grid = np.stack([r, g, b], axis=-1).reshape(-1, 3)
    return np.clip(transform.apply(grid), 0.0, 1.0)


def write_cube(
    transform: Transform, path: Path, size: int = 33, title: str | None = None
) -> Path:
    """Write a .cube 3D LUT. Loads in Resolve, Premiere, ffmpeg and friends."""
    values = sample_lattice(transform, size)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"# Generated by colorgrader ({transform.name} match, "
        f"strength {transform.strength:.2f})",
        f'TITLE "{title or path.stem}"',
        f"LUT_3D_SIZE {size}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
        "",
    ]
    lines.extend(f"{r:.6f} {g:.6f} {b:.6f}" for r, g, b in values)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_cdl(transform: Transform, path: Path, clip_id: str) -> Path | None:
    """Write an ASC CDL (.cdl) file. Resolve imports these directly.

    Returns None for transforms with no meaningful CDL (i.e. the reference).
    """
    if transform.cdl is None or transform.is_identity:
        return None

    c = transform.cdl
    # Blend toward identity so the file matches the strength used elsewhere.
    s = transform.strength
    slope = c.slope * s + 1.0 * (1 - s)
    offset = c.offset * s
    power = c.power * s + 1.0 * (1 - s)
    sat = c.saturation * s + 1.0 * (1 - s)

    fmt = lambda v: " ".join(f"{float(x):.6f}" for x in v)  # noqa: E731
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<ColorDecisionList xmlns="urn:ASC:CDL:v1.01">\n'
        "  <ColorDecision>\n"
        f'    <ColorCorrection id="{escape(clip_id)}">\n'
        "      <SOPNode>\n"
        f"        <Slope>{fmt(slope)}</Slope>\n"
        f"        <Offset>{fmt(offset)}</Offset>\n"
        f"        <Power>{fmt(power)}</Power>\n"
        "      </SOPNode>\n"
        "      <SatNode>\n"
        f"        <Saturation>{sat:.6f}</Saturation>\n"
        "      </SatNode>\n"
        "    </ColorCorrection>\n"
        "  </ColorDecision>\n"
        "</ColorDecisionList>\n",
        encoding="utf-8",
    )
    return path


def read_cube(path: Path) -> tuple[int, np.ndarray]:
    """Read a .cube file back. Used by the tests to verify round-tripping."""
    size = None
    values = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.upper().startswith("LUT_3D_SIZE"):
            size = int(line.split()[-1])
            continue
        parts = line.split()
        if len(parts) == 3:
            try:
                values.append([float(p) for p in parts])
            except ValueError:
                continue  # a keyword line such as TITLE or DOMAIN_MIN
    if size is None:
        raise ValueError(f"{path} has no LUT_3D_SIZE.")
    return size, np.array(values)
